import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
import "react-loading-skeleton/dist/skeleton.css";
import { Instances } from "@/init";
import Init from "./_shared/components/commun/init";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Tuzzo Shop",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Init></Init>
                <div className="vh-100">{children}</div>
            </body>
        </html>
    );
}
